### ISSUE TITLE
Is there a way to enable typing czech accents using long press (e.g 'r' — 'ř')

### ISSUE THREAD

**Issue by KolesnichenkoDS** [mariancerny/us-czech-keyboard-layout#3]
If you long press some characters in certain apps, there appears a popup with possible accents for this character. For example, if you long press `s` there appears a popup with accents `ß`, `ś` and `š`:
<img width="97" alt="image" src="https://user-images.githubusercontent.com/7870080/99803283-38799b00-2b4a-11eb-8e9c-44552f6efc95.png">
I don't know how customisable is it on layout level, but if it's possible, would be nice to enable this for `r` — `ř`, `e` — `ě`, `d` — `ď`, `y` — `ý`, `l` — `ľ` etc.

**Comment by peterpp** [comment]
I would say that the content of this popup menu is managed by the system automatically. And it depends on the keyboard language. There is no alternative character for `r` on the system U.S. keyboard. So maybe it is possible to start with Czech system keyboard and re-map all keys to US layout.

**Comment by mariancerny** [comment]
Thanks for the report. I do not use long press on keys to enter special characters so I have never noticed.
I have changed the language from en to cs inside the layout. That fixes the issue.
Reinstall the layout, reboot the mac, enjoy!

**Comment by KolesnichenkoDS** [comment]
@mariancerny that works, thank you very much!
